export enum EventBusType {
  TEST = 'test',
  CREATE_ORDER_SUCCESS = 'CREATE_ORDER_SUCCESS',
  FIND_CLOSET_SHOE_MAKERS = 'FIND_CLOSET_SHOE_MAKERS',
  UPDATE_STATUS_ORDER = 'UPDATE_STATUS_ORDER',
  CANCEL_ORDER_SUCCESS = 'CANCEL_ORDER_SUCCESS',
  FINISHED_ORDER = 'FINISHED_ORDER',
  HAVE_PERMISSION_LOCATION = 'HAVE_PERMISSION_LOCATION',
  BACK_TO_HOME = 'BACK_TO_HOME',
  // ... add more event types as needed
}
