export enum StatusActivity {
  NOT_FOUND = 'NOT_FOUND',
  WAITING = 'WAITING',
  SEARCHING = 'SEARCHING',
  MEETING = 'MEETING',
  INPROGRESS = 'INPROGRESS',
  COMPLETED = 'COMPLETED',
  ACCEPTED = 'ACCEPTED',
  CUSTOMER_CANCEL = 'CUSTOMER_CANCEL',
  FAILED = 'FAILED',
}

export enum TypePayment {
  CASH = 'CASH',
  CREDIT = 'CREDIT',
  CASH_AND_CREDIT = 'CASH_AND_CREDIT',
  OFFLINE_PAYMENT = 'OFFLINE_PAYMENT',
}
