export const Images = {
  Avatar: require('./images/avatar.png'),
  ShoeMaker: require('./images/shoeMaker.png'),
  Banner1: require('./images/banner-01.jpg'),
  Banner2: require('./images/banner-02.jpg'),
  Banner3: require('./images/banner-03.jpg'),
  Banner4: require('./images/banner-04.jpg'),
  Banner5: require('./images/banner-05.jpg'),
  Banner6: require('./images/banner-06.jpg'),
  Banner7: require('./images/banner-07.jpg'),
  Post1: require('./images/post1.png'),
  Post2: require('./images/post2.png'),
  Post3: require('./images/post3.png'),
  Post4: require('./images/post4.png'),
  Post5: require('./images/post5.png'),
  Post6: require('./images/post6.png'),
  Post7: require('./images/post7.png'),
  Post8: require('./images/post8.png'),
  Post9: require('./images/post9.png'),
  Post10: require('./images/post10.png'),
  Promotion: require('./images/promotion.png'),
}
